# Generated by Django 6.0.3 on 2026-03-18 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_categoria_venta_producto_activo_producto_sku_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='sku',
            field=models.CharField(default='SKU00', max_length=20, unique=True),
        ),
    ]
