# Generated by Django 6.0.3 on 2026-03-18 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_alter_producto_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='prefijo',
            field=models.CharField(default='GEN', max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='sku',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
    ]
