# Generated by Django 6.0.3 on 2026-03-18 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_categoria_prefijo_alter_producto_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='prefijo',
            field=models.CharField(default='GEN', max_length=3),
        ),
    ]
