# Generated by Django 6.0.3 on 2026-03-18 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_alter_categoria_prefijo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='prefijo',
        ),
        migrations.AlterField(
            model_name='producto',
            name='sku',
            field=models.PositiveIntegerField(editable=False, unique=True),
        ),
    ]
